// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var root = document.getElementById("root");

root.innerHTML = "<h1>Hello, world!</h1>";

var body = document.body;

body.style.backgroundColor = "#222831";

body.style.color = "#eeeeee";

exports.root = root;
exports.body = body;
/* root Not a pure module */
