// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


document.body.innerHTML = "<h1>Hello, world!</h1>";

document.body.style.backgroundColor = "#222831";

document.body.style.color = "#eeeeee";

/*  Not a pure module */
