// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var result = Caml_array.get(JSON.parse("{\"names\": [\"Luke\", \"Christine\"]}").names, 0);

var name = Caml_array.get(JSON.parse("{\"names\": [\"Luke\", \"Christine\"]}").names, 1);

exports.result = result;
exports.name = name;
/* result Not a pure module */
