// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(name, url, repositories, people) {
  return {
          name: name,
          url: url,
          repositories: repositories,
          people: people
        };
}

function linkTo(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

function updatePeople(t, count) {
  return {
          name: t.name,
          url: t.url,
          repositories: t.repositories,
          people: t.people + count | 0
        };
}

var GithubProject__OpaqueType = {
  make: make,
  linkTo: linkTo,
  updatePeople: updatePeople
};

var rails = {
  name: "Ruby on Rails",
  url: "https://rubyonrails.org",
  repositories: 99,
  people: 66
};

linkTo(rails);

var rails2 = updatePeople(rails, 5);

var Github_OT;

exports.GithubProject__OpaqueType = GithubProject__OpaqueType;
exports.Github_OT = Github_OT;
exports.rails = rails;
exports.rails2 = rails2;
/*  Not a pure module */
