// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function bookFormatToString(format) {
  switch (format) {
    case /* Hardcover */0 :
        return "Hardcover";
    case /* Paperback */1 :
        return "Paperback";
    case /* KindleEdition */2 :
        return "Kindle Edition";
    
  }
}

function drawRectangle(_rectangle) {
  
}

function drawLine(_line) {
  
}

function drawText(_text) {
  
}

function drawShape(shape) {
  switch (shape.TAG | 0) {
    case /* Rectangle */0 :
    case /* Line */1 :
    case /* Text */2 :
        return ;
    
  }
}

var codersAtWork = {
  title: "Coders at Work",
  tagline: "Reflections on the Craft of Programming",
  format: /* Paperback */1,
  availableInStock: 10
};

var block1 = {
  TAG: /* Rectangle */0,
  _0: {
    x: 100,
    y: 100,
    width: 50,
    height: 50
  }
};

var block2 = {
  TAG: /* Rectangle */0,
  _0: {
    x: 200,
    y: 100,
    width: 50,
    height: 50
  }
};

var block1ToBlock2 = {
  TAG: /* Line */1,
  _0: {
    x: 150,
    y: 125,
    length: 50
  }
};

var textLabel = {
  TAG: /* Text */2,
  _0: {
    text: "Connect",
    fontSize: /* Medium */1,
    fontFamily: /* Monospace */2
  }
};

exports.bookFormatToString = bookFormatToString;
exports.codersAtWork = codersAtWork;
exports.drawRectangle = drawRectangle;
exports.drawLine = drawLine;
exports.drawText = drawText;
exports.block1 = block1;
exports.block2 = block2;
exports.block1ToBlock2 = block1ToBlock2;
exports.textLabel = textLabel;
exports.drawShape = drawShape;
/* No side effect */
