// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function myCharRepeat(count, $$char) {
  var s = $$String.make(1, $$char);
  var _acc = s;
  var _times = count;
  while(true) {
    var times = _times;
    var acc = _acc;
    if (times < 2) {
      return acc;
    }
    var acc$prime = acc + s;
    _times = times - 1 | 0;
    _acc = acc$prime;
    continue ;
  };
}

myCharRepeat(6, /* "*" */42);

exports.myCharRepeat = myCharRepeat;
/*  Not a pure module */
