// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var dateFn = (function () {
  const o_date = new Intl.DateTimeFormat();
  const f_date = (m_ca, m_it) => Object({ ...m_ca, [m_it.type]: m_it.value });
  const { day, month, year } = o_date.formatToParts().reduce(f_date, {});
  return day + "/" + month + "/" + year;
});

Fs.readFile("./bsconfig.json", "utf8", (function (error, _data) {
        if (!(error == null)) {
          console.error("config file errro: ", error);
          return ;
        }
        
      }));

var result = Caml_array.get(JSON.parse("{\"names\": [\"Luke\", \"Christine\"]}").names, 0);

var name = Caml_array.get(JSON.parse("{\"names\": [\"Luke\", \"Christine\"]}").names, 1);

var counter = {
  contents: 0
};

function setCounter(step) {
  counter.contents = counter.contents + step | 0;
  
}

setCounter(1);

setCounter(2);

setCounter(3);

setCounter(4);

exports.dateFn = dateFn;
exports.result = result;
exports.name = name;
exports.counter = counter;
exports.setCounter = setCounter;
/*  Not a pure module */
