// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var configJSON = "{\n  \"name\": \"learn-rescript\",\n  \"version\": \"0.0.1\",\n  \"sources\": {\n    \"dir\": \"src\",\n    \"subdirs\": true\n  },\n  \"reason\": {\n    \"react-jsx\": 3\n  }\n}";

var config = JSON.parse(configJSON);

console.log(config.sources.subdirs);

console.log(config.reason["react-jsx"]);

var config2 = JSON.parse(configJSON);

exports.configJSON = configJSON;
exports.config = config;
exports.config2 = config2;
/* config Not a pure module */
