// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var sumOfFloats = 1 + 2.2 + 3.14;

var bookName = "Deep Work";

var tagline = "Rules for Focused Success in a Distracted World";

var book2 = "Real World OCaml: Functional programming for the masses";

var book = "Deep Work: Rules for Focused Success in a Distracted World";

var hello = "Hello, World!";

var goodbye = "Goodbye!";

var runningTotal = 1;

var sumOfInts = 10;

var joinedStrings = "Hello, World!";

var two = 2;

var one = 1;

var three = 3;

exports.hello = hello;
exports.goodbye = goodbye;
exports.runningTotal = runningTotal;
exports.sumOfInts = sumOfInts;
exports.sumOfFloats = sumOfFloats;
exports.joinedStrings = joinedStrings;
exports.bookName = bookName;
exports.tagline = tagline;
exports.book2 = book2;
exports.book = book;
exports.two = two;
exports.one = one;
exports.three = three;
/* No side effect */
