// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SimpleTest = require("./simpleTest.bs.js");

var names = [
  [
    "Jhumpa",
    "Lahiri"
  ],
  [
    "J. K",
    "Rowling"
  ],
  [
    "Devdutt",
    "Pattanaik"
  ]
];

var fullnames = [];

SimpleTest.assertEqual([
      "Jhumpa Lahiri",
      "J. K Rowling",
      "Devdutt Pattanaik"
    ], fullnames, "[exercise 3] generate array of full names");

exports.names = names;
exports.fullnames = fullnames;
/*  Not a pure module */
