// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function linkTo(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

var GithubProject = {
  linkTo: linkTo
};

var node = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 182,
  people: 375
};

linkTo(node);

var node2 = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 182,
  people: 385
};

var node3 = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 183,
  people: 385
};

exports.GithubProject = GithubProject;
exports.node = node;
exports.node2 = node2;
exports.node3 = node3;
/*  Not a pure module */
