// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function linkTo(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

var GithubProject__WithoutInterface = {
  linkTo: linkTo
};

var atom = {
  name: "Atom",
  url: "https://atom.io",
  repositories: 255,
  people: 56
};

linkTo(atom);

var GithubPWI;

var bookFormat = /* Paperback */1;

exports.GithubProject__WithoutInterface = GithubProject__WithoutInterface;
exports.GithubPWI = GithubPWI;
exports.atom = atom;
exports.bookFormat = bookFormat;
/*  Not a pure module */
