// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("./test.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function intAverage(_x, _y) {
  return Pervasives.failwith("For you to implement");
}

function floatAverage(_x, _y) {
  return Pervasives.failwith("For you to implement");
}

var firstName = "Fred";

var lastName = "Flintstone";

var fullName = "Fred Flintstone";

console.log("Hi, My name is ");

console.log(fullName);

console.log(" and I am 5 years old");

Test.runAll([
      [
        Pervasives.failwith("For you to implement") === 5,
        "int average"
      ],
      [
        Pervasives.failwith("For you to implement") === 5,
        "float average"
      ],
      [
        Pervasives.failwith("For you to implement") === 7.5,
        "float average"
      ]
    ]);

var four = 4;

var floatFour = 4;

var aBooleanFalse = false;

exports.four = four;
exports.floatFour = floatFour;
exports.intAverage = intAverage;
exports.floatAverage = floatAverage;
exports.firstName = firstName;
exports.lastName = lastName;
exports.fullName = fullName;
exports.aBooleanFalse = aBooleanFalse;
/*  Not a pure module */
