// Generated by ReScript, PLEASE EDIT WITH CARE


var sumOfFloats = 1 + 2.2 + 3.14;

var bookName = "Deep Work";

var tagline = "Rules for Focused Success in a Distracted World";

var book2 = "Real World OCaml: Functional programming for the masses";

var book = "Deep Work: Rules for Focused Success in a Distracted World";

function bookFormatToString(x) {
  switch (x) {
    case /* Hardcover */0 :
        return "Hardcover";
    case /* Paperback */1 :
        return "Paperback";
    case /* KindleEdition */2 :
        return "Kindle Edition";
    
  }
}

function isElectronic(x) {
  return x >= 2;
}

var hello = "Hello, World!";

var goodbye = "Goodbye!";

var runningTotal = 1;

var sumOfInts = 10;

var joinedStrings = "Hello, World!";

var two = 2;

var one = 1;

var three = 3;

var bookFormat2 = "Kindle Edition";

export {
  hello ,
  goodbye ,
  runningTotal ,
  sumOfInts ,
  sumOfFloats ,
  joinedStrings ,
  bookName ,
  tagline ,
  book2 ,
  book ,
  two ,
  one ,
  three ,
  bookFormatToString ,
  bookFormat2 ,
  isElectronic ,
  
}
/*  Not a pure module */
