// Generated by ReScript, PLEASE EDIT WITH CARE


var sumOfFloats = 1 + 2.2 + 3.14;

var bookName = "Deep Work";

var tagline = "Rules for Focused Success in a Distracted World";

var book2 = "Real World OCaml: Functional programming for the masses";

var book = "Deep Work: Rules for Focused Success in a Distracted World";

function bookFormatToString(x) {
  switch (x) {
    case /* Hardcover */0 :
        return "Hardcover";
    case /* Paperback */1 :
        return "Paperback";
    case /* KindleEdition */2 :
        return "Kindle Edition";
    
  }
}

function isElectronic(x) {
  return x >= 2;
}

function nextMoveBy(current) {
  switch (current) {
    case /* PlayerA */0 :
        return /* PlayerB */1;
    case /* PlayerB */1 :
        return /* PlayerC */2;
    case /* PlayerC */2 :
        return /* PlayerA */0;
    
  }
}

var secondMove = nextMoveBy(/* PlayerA */0);

var thirdMove = nextMoveBy(secondMove);

function formInputToHTML(x) {
  if (typeof x === "number") {
    return "<input type=\"submit\" />";
  }
  switch (x.TAG | 0) {
    case /* Text */0 :
        return "<input type=\"text\" name=\"" + x._0 + "\" />";
    case /* Number */1 :
        return "<input type=\"number\" name=\"" + x._0 + "\" min=\"" + String(x._1) + " max=\"" + String(x._2) + "\"/>";
    case /* Email */2 :
        return "<input type=\"email\" name=\"" + x._0 + "\" />";
    
  }
}

var nameInput = formInputToHTML({
      TAG: /* Text */0,
      _0: "name"
    });

var ageInput = formInputToHTML({
      TAG: /* Number */1,
      _0: "age",
      _1: 18,
      _2: 25
    });

var emailInput = formInputToHTML({
      TAG: /* Email */2,
      _0: "email"
    });

var hello = "Hello, World!";

var goodbye = "Goodbye!";

var runningTotal = 1;

var sumOfInts = 10;

var joinedStrings = "Hello, World!";

var two = 2;

var one = 1;

var three = 3;

var bookFormat2 = "Kindle Edition";

var firstMove = /* PlayerA */0;

var submit = "<input type=\"submit\" />";

export {
  hello ,
  goodbye ,
  runningTotal ,
  sumOfInts ,
  sumOfFloats ,
  joinedStrings ,
  bookName ,
  tagline ,
  book2 ,
  book ,
  two ,
  one ,
  three ,
  bookFormatToString ,
  bookFormat2 ,
  isElectronic ,
  nextMoveBy ,
  firstMove ,
  secondMove ,
  thirdMove ,
  formInputToHTML ,
  nameInput ,
  ageInput ,
  emailInput ,
  submit ,
  
}
/*  Not a pure module */
